twig:
    file_name_pattern: '*.twig'
    globals:
        stripe_public_key: '%stripe.public_key%'
        google_api_key: '%google.api.key%'
        stripe_dashboard_url: '%stripe.dashboard.url%'
    form_themes:
      [ 'form_div_layout.html.twig' ]

when@test:
    twig:
        strict_variables: true
