# config/packages/workflow.yaml
framework:
    workflows:
        order_completing:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Order

            initial_marking: created

            places:
                - created
                - delivery_choice
                - pending_payment
                - paid
                - to_prepare
                - pending_shipping
                - shipping
                - shipped
                - refund_pending
                - refund
                - refund_declined
                - cancelled

            transitions:
                to_delivery_choice:
                    from: created
                    to: delivery_choice

                to_pending_payment:
                    from: delivery_choice
                    to: pending_payment

                pay:
                    from: pending_payment
                    to: paid

                to_prepare:
                    from: paid
                    to: to_prepare

                to_pending_shipping:
                    from: to_prepare
                    to: pending_shipping

                shipping:
                    from: pending_shipping
                    to: shipping

                shipped:
                    from: shipping
                    to: shipped

                cancel:
                    from: [created, delivery_choice, pending_payment]
                    to: cancelled

                back_to_delivery_choice:
                    from: pending_payment
                    to: delivery_choice

                back_to_created:
                    from: [delivery_choice, pending_payment]
                    to: created

                to_refund_pending:
                    from: [shipped, shipping]
                    to: refund_pending

                to_refund:
                    from: refund_pending
                    to: refund

                to_refund_declined:
                    from: refund_pending
                    to: refund_declined
