# config/packages/workflow.yaml
framework:
    workflows:
        order_completing:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Order

            initial_marking: created

            places:
                - created
                - delivery_choice
                - pending_payment
                - paid
                - shipped
                - delivered
                - refund_pending
                - refund
                - canceled

            transitions:
                to_delivery_choice:
                    from: created
                    to: delivery_choice

                to_pending_payment:
                    from: delivery_choice
                    to: pending_payment

                pay:
                    from: pending_payment
                    to: paid

                ship:
                    from: paid
                    to: shipped

                deliver:
                    from: shipped
                    to: delivered

                cancel:
                    from: [created, delivery_choice, pending_payment]
                    to: canceled

                back_to_delivery_choice:
                    from: pending_payment
                    to: delivery_choice

                back_to_created:
                    from: [delivery_choice, pending_payment]
                    to: created

                to_refund_pending:
                    from: delivered
                    to: refund_pending

                to_refund:
                    from: refund_pending
                    to: refund
